#---------------------------------------------------------------------------------
# Clear the implicit built in rules
#---------------------------------------------------------------------------------
.SUFFIXES:
#---------------------------------------------------------------------------------

all:
	@$(MAKE) -C audiosync --no-print-directory

clean:
	@$(MAKE) -C audiosync clean --no-print-directory

.PHONY: all clean
